language: python
dist: xenial
python:
- 3.7
install:
- pip install pipenv
- pipenv install --system --deploy --ignore-pipfile
stages:
- test
- name: answers
  if: branch = master
jobs:
  include:
  - stage: test
    install:
      - pipenv install --dev --ignore-pipfile --deploy
    script: pytest
    before_script:
      - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        > ./cc-test-reporter
      - chmod +x ./cc-test-reporter
      - "./cc-test-reporter before-build"
    after_script:
      - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"