language: python
dist: xenial
python:
- 3.7
install:
- pip install pipenv
- pipenv install --system --deploy --ignore-pipfile
stages:
- test
- name: answers
  if: branch = master
jobs:
  include:
  - stage: test
    install:
      - pipenv install --dev --ignore-pipfile --deploy
    script: pytest


