name: SPR_Create_Dotmatics_ADLP_File
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - rdkit
  - pip=20.0.2=py_2
  - setuptools=46.1.3=py37hc8dfbb8_0
  - pip:
    - click==7.1.1
    - cx-oracle==7.3.0
    - numpy==1.18.2
    - pytest==5.4.1
    - pytest-cov==2.8.1
    - setuptools-scm==3.5.0
    - sqlalchemy==1.3.16
    - xlrd==1.2.0
    - xlsxwriter==1.2.8
#prefix: /Users/bfulroth/.conda/envs/SPR_Create_Dotmatics_ADLP_File