name: SPR_ADLP_ENV_3
channels:
  - conda-forge
  - kadrlica
  - jsandhu
  - signals
  - defaults
dependencies:
  - pandas==1.3.0
  - pip=20.0.2
  - numpy==1.21.0
  - rdkit==2021.03.3
  - oracle-instantclient
  - setuptools==49.6.0
  - cryptography==3.4.7
  - click==8.0.1
  - pytest==6.2.4
  - pytest-cov==2.12.1
  - python-dotenv==0.18.0
  - setuptools-scm==6.0.1
  - sqlalchemy==1.4.20
  - xlrd==2.0.1
  - xlsxwriter==1.4.4
  - openpyxl==3.0.7
  - pip:
    - cx-oracle==8.2.1